### ISSUE TITLE
relationship between huggingface blog and repo

### ISSUE THREAD

**Issue by insublee** [AlekseyKorshuk/chat-data-pipeline#2]
Hello, I am writing to compliment this wonderful repository.
But there is one question. I am curious about the relationship between the author of [this blog](https://huggingface.co/blog/dedup) and the author of the this repository. 
The blog post and the code in this repository are quite similar, but I can't find any references to each other.
Can you explain what happened?

**Comment by AlekseyKorshuk** [comment]
MinHash deduplication code was adapted from BigCode Project codebase: 

<img width="988" alt="Screenshot 2024-01-17 at 12 11 44" src="https://github.com/AlekseyKorshuk/chat-data-pipeline/assets/48794610/cd379cf5-6dc5-4fc5-b90a-0a3e9323e9ca">
